import { Outfit} from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const outfit = Outfit({
  subsets: ['latin'],
  weight: ["400","500","600","700"],
});

export const metadata = {
  title: "BLog-App",
  description: "Generated by Shubam Gupta",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      //   className={`${outfit.variable} antialiased`}
      // >
      className={outfit.variable}
      >
        {children}
      </body>
    </html>
  );
}
